version: "3.7"
services:
  php:
    build:
      args:
        uname: ${PHP_UNAME}
        uid: ${PHP_UID}
        gid: ${PHP_GID}
      context: ./docker-compose/php-fpm
      dockerfile: Dockerfile
    environment:
      COMPOSER_MEMORY_LIMIT: 2G
      XDEBUG_CONFIG: remote_autostart=${XDEBUG_REMOTE_AUTOSTART} remote_handler=${XDEBUG_REMOTE_HANDLER} remote_connect_back=${XDEBUG_REMOTE_CONNECTION_BACK} idekey=${XDEBUG_IDEKEY} client_host=${XDEBUG_REMOTE_HOST} client_port=${XDEBUG_STORM_PORT} remote_enable=1
      PHP_IDE_CONFIG: serverName=${XDEBUG_STORM_SERVER_NAME}
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./project:/var/www/html
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
          - ${PMA_PORT}:80
      restart: unless-stopped      
  nginx:
    image: nginx
    volumes:
        - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./project:/var/www/html
    depends_on:
        - php
    ports:
      - ${NGINX_PORT}:80
    restart: unless-stopped